#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mako
Version  : 1.4.1
Release  : 1
URL      : https://github.com/emersion/mako/archive/v1.4.1.tar.gz
Source0  : https://github.com/emersion/mako/archive/v1.4.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mako-bin = %{version}-%{release}
Requires: mako-data = %{version}-%{release}
Requires: mako-man = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(pango)
BuildRequires : pkgconfig(scdoc)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(wayland-protocols)

%description
# mako
A lightweight notification daemon for Wayland. Works on Sway.
<p align="center">
<img src="https://sr.ht/meoc.png" alt="mako screenshot">
</p>

%package bin
Summary: bin components for the mako package.
Group: Binaries
Requires: mako-data = %{version}-%{release}

%description bin
bin components for the mako package.


%package data
Summary: data components for the mako package.
Group: Data

%description data
data components for the mako package.


%package man
Summary: man components for the mako package.
Group: Default

%description man
man components for the mako package.


%prep
%setup -q -n mako-1.4.1
cd %{_builddir}/mako-1.4.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1581802408
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mako
/usr/bin/makoctl

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/services/fr.emersion.mako.service

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/mako.1
/usr/share/man/man1/makoctl.1
/usr/share/man/man5/mako.5
